name: Publish Release

on:
  push:
    tags:
      - 'v*' # Se déclenche à chaque tag v1.0.0, v0.0.2, etc.

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Installation des dépendances
        run: npm ci

      - name: Compilation du package VSIX
        run: npx @vscode/vsce package

      # --- ÉTAPE AJOUTÉE POUR L'OPTION A ---
      - name: Renommer le package pour URL fixe
        run: mv *.vsix experdeploy.vsix

      - name: Création de la Release GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: 'experdeploy.vsix' # On cible uniquement le fichier renommé
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}